services:
  api_service:
    build:
      context: api_service
      dockerfile: Dockerfile
    image: planserviciodaniq.azurecr.io/api_service:v1
    container_name: api_service
    environment:
      - GEMINI_API_KEY=AIzaSyDej1B3F3w877xxNtz_QDXwycIW05yoksA
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"