version: "3.9"

services:
  api_service:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    image: planservicioia.azurecr.io/api_service:${TAG}
    container_name: api_service
    volumes:
      - ./data:/app/data
    env_file:
      - ./api_service/.env
    networks:
      - backend
  relay_service:
    build:
      context: ./relay_service
      dockerfile: Dockerfile
    image: planservicioia.azurecr.io/relay_service:${TAG}
    container_name: relay_service
    ports:
      - "8080:8000"
    env_file:
      - ./relay_service/.env
    depends_on:
      - api_service
    networks:
      - backend

networks:
  backend:
    driver: bridge